update-permission: "cosmicmining.update"
bypass_permission: "cosmicmining.bypass"

blocks:
  STONE:
    respawn-time: 3
    required-pickaxe: WOODEN_PICKAXE
    experience-dropped: 5
  COAL_ORE:
    respawn-time: 10
    required-pickaxe: STONE_PICKAXE
    experience-dropped: 10
  GOLD_ORE:
    respawn-time: 15
    required-pickaxe: IRON_PICKAXE
    experience-dropped: 15
  IRON_ORE:
    respawn-time: 40
    required-pickaxe: DIAMOND_PICKAXE
    experience-dropped: 20
  DIAMOND_ORE:
    respawn-time: 60
    required-pickaxe: NETHERITE_PICKAXE
    experience-dropped: 25

level-ups:
  experience-to-level:
    5: 100
    10: 150
    20: 225
    40: 300
    55: 370
    75: 450
    80: 500
    90: 700
    91: 800
    92: 850
    93: 900
    94: 1000
    100: 1100

pickaxes:
  WOODEN_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 1
  STONE_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 1.3
  GOLDEN_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 1.4
  IRON_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 1.7
  DIAMOND_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 2
  NETHERITE_PICKAXE:
    required-level: 0
    base-max-experience: 100
    per-level-multiplier: 2.2

armors:
  LEATHER_ARMOR:
    required-level: 10
    base-max-experience: 100
    per-level-multiplier: 1
  CHAINMAIL_ARMOR:
    required-level: 25
    base-max-experience: 200
    per-level-multiplier: 1.3
  GOLDEN_ARMOR:
    required-level: 40
    base-max-experience: 250
    per-level-multiplier: 1.4
  IRON_ARMOR:
    required-level: 50
    base-max-experience: 300
    per-level-multiplier: 1.7
  DIAMOND_ARMOR:
    required-level: 70
    base-max-experience: 350
    per-level-multiplier: 2
  NETHERITE_ARMOR:
    required-level: 90
    base-max-experience: 400
    per-level-multiplier: 2.2

required-levels:
  items:
    WOODEN_PICKAXE: 0
    STONE_PICKAXE: 15
    GOLDEN_PICKAXE: 40
    IRON_PICKAXE: 50
    DIAMOND_PICKAXE: 70
    NETHERITE_PICKAXE: 90
  armors:
    NETHERITE_HELMET: 90
    NETHERITE_CHESTPLATE: 90
    NETHERITE_LEGGINGS: 90
    NETHERITE_BOOTS: 90
    DIAMOND_HELMET: 70
    DIAMOND_CHESTPLATE: 70
    DIAMOND_LEGGINGS: 70
    DIAMOND_BOOTS: 70
    IRON_HELMET: 50
    IRON_CHESTPLATE: 50
    IRON_LEGGINGS: 50
    IRON_BOOTS: 50
    GOLDEN_HELMET: 40
    GOLDEN_CHESTPLATE: 40
    GOLDEN_LEGGINGS: 40
    GOLDEN_BOOTS: 40
    CHAINMAIL_HELMET: 25
    CHAINMAIL_CHESTPLATE: 25
    CHAINMAIL_LEGGINGS: 25
    CHAINMAIL_BOOTS: 25
    LEATHER_HELMET: 10
    LEATHER_CHESTPLATE: 10
    LEATHER_LEGGINGS: 10
    LEATHER_BOOTS: 10