update-permission: "cosmicmining.update"
bypass_permission: "cosmicmining.bypass"

required-levels:
  items:
    wooden_pickaxe: 0
    stone_pickaxe: 15
    golden_pickaxe: 40
    iron_pickaxe: 50
    diamond_pickaxe: 70
    netherite_pickaxe: 90
  armors:
    netherite_helmet: 90
    netherite_chestplate: 90
    netherite_leggings: 90
    netherite_boots: 90
    diamond_helmet: 70
    diamond_chestplate: 70
    diamond_leggings: 70
    diamond_boots: 70
    iron_helmet: 50
    iron_chestplate: 50
    iron_leggings: 50
    iron_boots: 50
    golden_helmet: 40
    golden_chestplate: 40
    golden_leggings: 40
    golden_boots: 40
    chainmail_helmet: 25
    chainmail_chestplate: 25
    chainmail_leggings: 25
    chainmail_boots: 25
    leather_helmet: 10
    leather_chestplate: 10
    leather_leggings: 10
    leather_boots: 10

blocks:
  stone:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 1
  coal_ore:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 2
  gold_ore:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 3
  iron_ore:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 4
  diamond_ore:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 5

level-ups:
  to-level:
    5: 100
    10: 150
    20: 225
    40: 300
    55: 370
    75: 450
    80: 500
    90: 700
    91: 800
    92: 850
    93: 900
    94: 1000
    100: 1100