name: CosmicMining
version: ${project.version}
aliases: mr
main: io.github.goldeneas.cosmicmining.CosmicMining
author: Goldeneas
library:
  - org.xerial:sqlite-jdbc:3.42.0.0
api-version: '1.20'
softdepend: [PlaceholderAPI]
permissions:
  cosmicmining.bypass:
    default: op
    description: bypass plugin
  cosmicmining.update:
    default: op
    description: get a notification about plugin's updates
