bypass_permission: "miningrestrictions.bypass"

items:
  levels_required:
    wooden_pickaxe: 0
    stone_pickaxe: 10
    golden_pickaxe: 15
    iron_pickaxe: 25
    diamond_pickaxe: 35
    netherite_pickaxe: 50

blocks:
  exp_given:
    stone: 1
    coal_ore: 2
    gold_ore: 3
    iron_ore: 4
    diamond_ore: 5

required_experience:
  till_level:
    5: 100
    10: 150
    20: 225
    40: 300
    55: 370
    75: 450
    80: 500
    90: 700
    91: 800
    92: 850
    93: 900
    94: 1000
    100: 1100