update-permission: "cosmicmining.update"
bypass_permission: "cosmicmining.bypass"

required-levels:
  items:
    WOODEN_PICKAXE: 0
    STONE_PICKAXE: 15
    GOLDEN_PICKAXE: 40
    IRON_PICKAXE: 50
    DIAMOND_PICKAXE: 70
    NETHERITE_PICKAXE: 90
  armors:
    NETHERITE_HELMET: 90
    NETHERITE_CHESTPLATE: 90
    NETHERITE_LEGGINGS: 90
    NETHERITE_BOOTS: 90
    DIAMOND_HELMET: 70
    DIAMOND_CHESTPLATE: 70
    DIAMOND_LEGGINGS: 70
    DIAMOND_BOOTS: 70
    IRON_HELMET: 50
    IRON_CHESTPLATE: 50
    IRON_LEGGINGS: 50
    IRON_BOOTS: 50
    GOLDEN_HELMET: 40
    GOLDEN_CHESTPLATE: 40
    GOLDEN_LEGGINGS: 40
    GOLDEN_BOOTS: 40
    CHAINMAIL_HELMET: 25
    CHAINMAIL_CHESTPLATE: 25
    CHAINMAIL_LEGGINGS: 25
    CHAINMAIL_BOOTS: 25
    LEATHER_HELMET: 10
    LEATHER_CHESTPLATE: 10
    LEATHER_LEGGINGS: 10
    LEATHER_BOOTS: 10

blocks:
  STONE:
    respawn-time: 20
    required-item: WOODEN_PICKAXE
    experience-dropped: 1
  COAL_ORE:
    respawn-time: 20
    required-item: STONE_PICKAXE
    experience-dropped: 2
  GOLD_ORE:
    respawn-time: 20
    required-item: IRON_PICKAXE
    experience-dropped: 3
  IRON_ORE:
    respawn-time: 20
    required-item: DIAMOND_PICKAXE
    experience-dropped: 4
  DIAMOND_ORE:
    respawn-time: 20
    required-item: NETHERITE_PICKAXE
    experience-dropped: 5

level-ups:
  to-level:
    5: 100
    10: 150
    20: 225
    40: 300
    55: 370
    75: 450
    80: 500
    90: 700
    91: 800
    92: 850
    93: 900
    94: 1000
    100: 1100