name: MiningRestrictions
version: '1.3.0'
main: io.github.goldeneas.miningrestrictions.MiningRestrictions
api-version: '1.20'
permissions:
  miningrestrictions.bypass:
    default: op
    description: bypass mining restrictions
