name: CosmicMining
version: '1.3.2'
aliases: mr
main: io.github.goldeneas.cosmicmining.CosmicMining
author: Goldeneas
library:
  - org.xerial:sqlite-jdbc:3.42.0.0
api-version: '1.20'
permissions:
  cosmicmining:
    default: op
    description: bypass plugin
